---
dependencies:
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      # with rsync
      upload_helm_chart_src: "{{ test_relative_path }}"
      upload_helm_chart_dest: /usr/local/src/chart-one
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      # with multi_copy
      upload_helm_chart_src: "{{ test_relative_path }}"
      upload_helm_chart_dest: /usr/local/src/chart-two
      upload_helm_chart_method: copy
