# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Set node selector for openstack-resource-controller
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: orc-controller-manager
        namespace: orc-system
      spec:
        template:
          spec:
            nodeSelector: "{{ openstack_resource_controller_node_selector }}"
