name: bump

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - run: ./hack/bump/kubernetes.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
          push-to-fork: vexxhost-bot/ansible-collection-kubernetes
          commit-message: "chore(deps): update kubernetes"
          signoff: true
          branch: bump/kubernetes
          delete-branch: true
          title: "chore(deps): update kubernetes"
          body: |
            ## Automated `kubernetes` update

            This PR updates the `kubernetes` binaries to the latest versions.
